#!/bin/bash
# Vendors the Live2D Cubism SDK for Native into an ignored local directory.
#
# The SDK is not redistributable, so nothing it produces may be committed. This
# script is the documented setup step that makes a Live2D-enabled build possible
# on one workstation:
#
#   Tools/setup_live2d.sh ~/Documents/design/CubismSdkForNative-5-r-2.5
#
# It produces Vendor/Live2D/{Core,Framework,Live2DCubismCore.xcframework}. The
# static Core arrives as one archive per slice, which Xcode cannot consume
# directly, so the simulator slices are merged and wrapped in an XCFramework.
set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <path to CubismSdkForNative directory>" >&2
    exit 2
fi

SDK="${1%/}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR="$REPO/Vendor/Live2D"

for required in "$SDK/Core/include/Live2DCubismCore.h" "$SDK/Framework/src" "$SDK/LICENSE.md"; do
    if [ ! -e "$required" ]; then
        echo "error: $required not found; is $SDK a Cubism SDK for Native directory?" >&2
        exit 1
    fi
done

echo "==> vendoring into $VENDOR"
rm -rf "$VENDOR"
mkdir -p "$VENDOR"
cp -R "$SDK/Core" "$VENDOR/Core"
cp -R "$SDK/Framework" "$VENDOR/Framework"
# Retain the licence next to the code it governs.
cp "$SDK/LICENSE.md" "$VENDOR/LICENSE.md"
cp "$SDK/cubism-info.yml" "$VENDOR/cubism-info.yml"

# Only the Metal renderer is compiled. Removing the other backends keeps them
# from being pulled into the target by a directory-wide source rule.
for backend in OpenGL D3D9 D3D11 Vulkan; do
    rm -rf "$VENDOR/Framework/src/Rendering/$backend"
done

echo "==> building Live2DCubismCore.xcframework"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

SIM_LIBS=()
for slice in Release-iphonesimulator-arm64 Release-iphonesimulator-x86_64; do
    if [ -f "$VENDOR/Core/lib/ios/$slice/libLive2DCubismCore.a" ]; then
        SIM_LIBS+=("$VENDOR/Core/lib/ios/$slice/libLive2DCubismCore.a")
    fi
done
if [ ${#SIM_LIBS[@]} -eq 0 ]; then
    echo "error: no simulator Core slice found" >&2
    exit 1
fi
lipo -create "${SIM_LIBS[@]}" -output "$WORK/libLive2DCubismCore-sim.a"

mkdir -p "$WORK/include"
cp "$VENDOR/Core/include/Live2DCubismCore.h" "$WORK/include/"

rm -rf "$VENDOR/Live2DCubismCore.xcframework"
xcodebuild -create-xcframework \
    -library "$VENDOR/Core/lib/ios/Release-iphoneos/libLive2DCubismCore.a" -headers "$WORK/include" \
    -library "$WORK/libLive2DCubismCore-sim.a" -headers "$WORK/include" \
    -output "$VENDOR/Live2DCubismCore.xcframework" >/dev/null

cat > "$VENDOR/README.md" <<'NOTE'
This directory is generated by `Tools/setup_live2d.sh` and is intentionally
untracked. The Live2D Cubism SDK is not redistributable: do not commit anything
here, and do not copy it into the App bundle beyond the linked Core library and
the compiled shader libraries.
NOTE

echo "==> done"
echo "    $(ls "$VENDOR")"
echo
echo "Generate the Live2D-enabled project with:"
echo "    xcodegen generate --spec project.live2d.yml"
