#!/bin/bash
# Vendors VRMMetalKit into an ignored local directory.
#
# VRMMetalKit is Apache-2.0, so unlike the Cubism SDK it *could* be fetched by
# SwiftPM directly. It is vendored instead for two reasons: a 49 MB fetch is
# painful on a slow link, and pinning a local tree makes the exact reviewed
# revision the thing that builds rather than whatever a branch points at today.
#
#   Tools/setup_vrm.sh ~/Downloads/VRMMetalKit-main.zip
#
# Produces Vendor/VRMMetalKit/ plus a recorded revision. Nothing here is
# committed; `Vendor/` is ignored.
set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <VRMMetalKit zip or checkout directory>" >&2
    exit 2
fi

SOURCE="${1%/}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR="$REPO/Vendor/VRMMetalKit"
# The revision this integration was reviewed and spiked against.
EXPECTED_REVISION="8d87fd565c7629881cea980752c9d5518a504c7d"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "==> staging $SOURCE"
if [ -d "$SOURCE" ]; then
    cp -R "$SOURCE" "$WORK/tree"
elif [ -f "$SOURCE" ]; then
    unzip -q "$SOURCE" -d "$WORK/unzipped"
    # A GitHub archive expands to a single <repo>-<ref> directory.
    inner="$(find "$WORK/unzipped" -maxdepth 1 -mindepth 1 -type d | head -1)"
    if [ -z "$inner" ]; then
        echo "error: archive did not contain a directory" >&2
        exit 1
    fi
    mv "$inner" "$WORK/tree"
else
    echo "error: $SOURCE is neither a directory nor a file" >&2
    exit 1
fi

for required in "$WORK/tree/Package.swift" "$WORK/tree/Sources/VRMMetalKit" "$WORK/tree/LICENSE"; do
    if [ ! -e "$required" ]; then
        echo "error: $required missing; is this a VRMMetalKit checkout?" >&2
        exit 1
    fi
done

# Tests are kept even though the app never builds them: the package manifest
# declares those targets, and SwiftPM refuses to load a package whose declared
# target paths are missing. Only CI config is dropped.
rm -rf "$WORK/tree/.github"

echo "==> vendoring into $VENDOR"
rm -rf "$VENDOR"
mkdir -p "$(dirname "$VENDOR")"
mv "$WORK/tree" "$VENDOR"

echo "$EXPECTED_REVISION" > "$VENDOR/JOI_REVISION"
cat > "$VENDOR/JOI_README.md" <<NOTE
Generated by \`Tools/setup_vrm.sh\` and intentionally untracked.

Reviewed revision: \`$EXPECTED_REVISION\`

VRMMetalKit is Apache-2.0. Its LICENSE and NOTICE are retained here, and the
attribution required for redistribution is recorded in the repository's
THIRD_PARTY_NOTICES.md. Do not commit this directory: the app declares it as a
local package so the reviewed revision is what builds.
NOTE

echo "==> done"
echo "    revision $EXPECTED_REVISION"
echo
echo "Generate the native (Live2D + VRM) project with:"
echo "    xcodegen generate --spec project.native.yml"
